### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by aehlke** [ianstormtaylor/slate-auto-replace-text#1]
Is this deprecated in favor of `slate-auto-replace` now? There are some existing references to this one in Slate.

**Comment by ianstormtaylor** [comment]
Good question! My plan is actually to make this plugin use the more generic `slate-auto-replace` under the covers, but keep this one around since it has a nicer API if you are simply doing a lot of text-only replacements.

**Comment by oyeanuj** [comment]
@ianstormtaylor Is that still the plan? I see that both the components still have different source code with the other plugin more recently updated with fixes, etc.

Also, happy to make a Readme PR to reflect your response!

**Comment by ianstormtaylor** [comment]
Yeah might as well deprecate this actually since I'm not even using the nicer syntax for the replacements I'm doing, easier to have it all in once place. I'll edit the readme. Thanks!
